name: Destroy Resources

on:
  workflow_dispatch:  # Manually trigger the action

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Pulumi
      - name: Set up Pulumi
        uses: pulumi/actions/setup-pulumi@v3
        with:
          pulumi-version: "latest"

      # Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"  # Replace with your AWS region

      # Install dependencies (if you're using Node.js)
      - name: Install dependencies
        run: npm install

      # Run Pulumi destroy to tear down the resources
      - name: Destroy Pulumi stack
        run: pulumi destroy --yes --stack Kulwinder-lab08-pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Optionally, verify resources destruction
      - name: Verify resources destruction
        run: |
          aws s3 ls s3://mybucket-c187005 || echo "Bucket has been destroyed"
          aws cloudfront list-distributions || echo "CloudFront distribution has been destroyed"
