name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test credentials
      run: echo $AWS_ACCESS_KEY_ID
           echo $AWS_SECRET_ACCESS_KEY
    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::484907508139:role/GitHubActionsOIDC
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - name: Assume Role with GitHub OIDC Token
      run: |
        # Get the OIDC token from GitHub Actions
        OIDC_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        
        # Use AWS CLI to assume the role using the OIDC token
        aws sts assume-role-with-web-identity \
          --role-arn arn:aws:iam::484907508139:role/GitHubActionsOIDC \
          --role-session-name GitHubOIDCSession \
          --web-identity-token $OIDC_TOKEN
        
    - name: Install dependencies
      run: npm install

    - name: Set up Pulumi
      uses: pulumi/actions@v3
      with:
        command: up
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
