name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required to read the repo contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::688567283850:role/GitHubActionsOIDC
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - name: Install dependencies
      run: npm install

    - name: Set up Pulumi
      uses: pulumi/actions@v3
      with:
        command: up
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
