name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::484907508139:role/GitHubActionsOIDC
        aws-region: us-east-1

<<<<<<< HEAD
      - name: Install dependencies
        run: npm install

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::484907508139:role/GitHubActionsOIDC
          aws-region: us-east-1

      - name: Set up Pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
=======
    - name: Install dependencies
      run: |
        npm install
        npx pulumi stack select dev
>>>>>>> 573ebe2f7634dfea125967344f4ecee5cb8bcdd0

    - name: Deploy with Pulumi
      run: |
        npx pulumi up --yes
