name: Deploy to AWS
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout-code
      uses: actions/checkout@v4
 
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::484907508139:role/GitHubActionsOIDC
        aws-region: us-east-1
 
    - name: Verify AWS authentication
      run: aws sts get-caller-identity
 
    - name: Install dependencies
      run: npm install
 
    - name: Set up Pulumi
      uses: pulumi/actions@v3
      with:
        command: up
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ROLE_ARN: arn:aws:iam::688567283850:user/lab8